services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "tg_shop_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    networks:
      - app-network

  migrate:
    build:
      context: .
    env_file: .env
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - app-network

  bot:
    build:
      context: .
    env_file: .env
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
