"""empty message

Revision ID: 0087390f0750
Revises: 9e9df58c4798
Create Date: 2026-05-26 14:41:57.976303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0087390f0750'
down_revision: Union[str, Sequence[str], None] = '9e9df58c4798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('size', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'size')
    # ### end Alembic commands ###
