"""remove balance from users

Revision ID: 32384bad6f22
Revises: c22117262623
Create Date: 2026-05-29 15:21:34.279666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32384bad6f22'
down_revision: Union[str, Sequence[str], None] = 'c22117262623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
